# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkey', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('summary', models.TextField()),
                ('rating', models.CharField(max_length=50)),
                ('diversity_score', models.IntegerField()),
                ('bechdel_test', models.BooleanField()),
                ('release_date', models.DateField()),
                ('activate', models.BooleanField()),
            ],
        ),
    ]
