# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated_Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkey', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
    ]
